### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by HappyBoBo0331** [lxc86739795/parsing_platform#1]
Hello Doc Liu!I am very interested in this work.When I run the code,I wonder how I can get the pth file of the HRNet pretrained model.Or if you can offer me a MVP trained model?

**Comment by lxc86739795** [comment]
> Hello Doc Liu!I am very interested in this work.When I run the code,I wonder how I can get the pth file of the HRNet pretrained model.Or if you can offer me a MVP trained model?

Hi,
You can download the HRNet model pretrained on MVP-coarse from https://github.com/lxc86739795/parsing_platform/releases/download/v0.1/hrnet_mvp_coarse.pth
and the model pretrained on MVP-fine from 
https://github.com/lxc86739795/parsing_platform/releases/download/v0.1/hrnet_mvp_fine.pth

The HRNet model pretrained on ImageNet can be found from its official site: 
https://github.com/HRNet/HRNet-Semantic-Segmentation

Best,
Xinchen
