### ISSUE TITLE
 Vehicle reid dateset parsing

### ISSUE THREAD

**Issue by viwa-creatr** [lxc86739795/parsing_platform#3]
How to use the trained model HRNet to parse the vehicle reid dateset, such as VeRi776 or Veri-wild. Please help me！

**Comment by lxc86739795** [comment]
> How to use the trained model HRNet to parse the vehicle reid dateset, such as VeRi776 or Veri-wild. Please help me！

Please use this script: human_vehicle_parsing_platform/train_test/HRNet/run_test.sh
The path to the pretrained model and dataset directory should be changed.

**Comment by viwa-creatr** [comment]
Thank you, I will try it
