### ISSUE TITLE
Question: Inference code

### ISSUE THREAD

**Issue by hanlanqian** [lxc86739795/parsing_platform#4]
刘博士您好，我想在自己的数据集上使用您的这个项目，请问有可以使用的推理代码吗(. .)

**Comment by lxc86739795** [comment]
请参考另一个issue #3

**Comment by hanlanqian** [comment]
打扰一下，请问这个路径下的文件代表什么呢
`list_path = os.path.join('/home/liuwu1/notespace/dataset/LIP/LIP_CIHP_train_path_new.txt')`
