### ISSUE TITLE
networks.CE2P has no module Res_Deeplab

### ISSUE THREAD

**Issue by Darknesszlx** [lxc86739795/parsing_platform#5]
https://github.com/lxc86739795/human_vehicle_parsing_platform/blob/524168d3101b5f57291e643b4c6d386969a7ddff/train_test/DenseASPP/test.py#L6
https://github.com/lxc86739795/human_vehicle_parsing_platform/blob/524168d3101b5f57291e643b4c6d386969a7ddff/train_test/Deeplabv3/test.py#L6

**Comment by lxc86739795** [comment]
Its name has changed to CE2P_Deeplab. Please use CE2P_Deeplab instead of Res_Deeplab.
